[package]
name = "promethee"
version = "0.1.0"
authors = ["Daniel Mitre <daniel.mitre@ccc.ufcg.edu.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
num = "0.3.0"